spec:
  template:
    spec:
      # Declare a volume mounting the config map
      volumes:
        - configMap:
            # Name of the config map
            name: app-config
            optional: true
            # Define the items from the config map to mount
            items:
            - key: app-config.yml
              path: config.yml
            # Volume name (used as reference below)
          name: config
      containers:
        - env:
            - name: VERTX_CONFIG_PATH
              value: '/deployments/conf/config.yml'
          volumeMounts:
            - name: config
              mountPath: /deployments/conf
