apiVersion: v1
kind: List
items:
- apiVersion: authorization.openshift.io/v1
  kind: RoleBinding
  metadata:
    name: role-view-default
    labels:
      example: 
  subjects:
  - kind: ServiceAccount
    name: default
  roleRef:
    name: view
