apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: role-view-default
    labels:
      booster: 
  subjects:
  - kind: ServiceAccount
    name: default
  roleRef:
    name: view
